#!/bin/sh

### BEGIN INIT INFO
# Provides:          pihole-control
# Required-Start:    $remote_fs $syslog $dnsmasq
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Pi-hole control button handler
# Description:       Enables and disables Pi-hole with a physical push button and shows the current state with a LED"
### END INIT INFO

# Change the next 4 lines to suit where you install your script and what you want to call it
DIR=/home/pi
LOG_DIR=$DIR
DAEMON=$DIR/pihole-control.py
DAEMON_NAME=pihole-control

# Add any command line options for your daemon here
DAEMON_OPTS="-l DEBUG -lf ${LOG_DIR}/${DAEMON_NAME}.log"

# This next line determines what user the script runs as.
DAEMON_USER=pi

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --chdir $DIR --startas $DAEMON -- $DAEMON_OPTS
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0